inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15
  ExcludedMethods:
    - earliest_year
    - latest_year

Metrics/ModuleLength:
  Exclude:
    - lib/parse_date/int_from_string.rb

Style/NumericLiterals:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Exclude:
    - spec/**/*

Style/TrailingCommaInArrayLiteral:
  Exclude:
    - spec/**/*

Style/WordArray:
  Enabled: false

Style/YodaCondition:
  Enabled: false
