inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 22

Style/NumericLiterals:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Exclude:
    - spec/**/*

Style/WordArray:
  Enabled: false

Style/YodaCondition:
  Enabled: false
