inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/WordArray:
  Enabled: false

Style/YodaCondition:
  Enabled: false
